### ISSUE TITLE
Update Composer Requirement

### ISSUE THREAD

**Issue by sprankhub** [magento/composer-root-update-plugin#14]
The current version of Composer is `1.10.8`. This repository specifically only supports Composer up to `1.10.6`. Any reason? I do understand that you cannot easily support Composer 2, but shouldn't the latest Composer 1 version be supported? :)

**Comment by pdohogne-magento** [comment]
Thank you for your comment!

We depend on private Composer code, and semantic versioning rules dictate that private code can change in patch releases, so we cannot guarantee that the plugin will always be compatible with the new Composer releases, even at the patch level.  We have not yet tested the plugin on the latest Composer release, so it is currently still limited to the Composer versions that were available at the time of the most recent plugin release.  If you need a feature from a version of Composer that is not currently compatible with the plugin, please let us know and we will look into whether or not the plugin can be made compatible.  Otherwise, the plugin's Composer constraint will be updated at the time of its next release.

**Comment by pdohogne-magento** [comment]
Version 1.1.0 will update the Composer 1 requirement to 1.10.19
