### ISSUE TITLE
Doesn't work with Composer 2

### ISSUE THREAD

**Issue by marcinsdance** [magento/composer-root-update-plugin#18]
Output when using Composer 2:

```
Creating a "magento/project-community-edition" project at "/tmp/exampleproject"
Installing magento/project-community-edition (2.4.1)
  - Downloading magento/project-community-edition (2.4.1)
  - Installing magento/project-community-edition (2.4.1): Extracting archive
Created project in /tmp/exampleproject
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires magento/composer-root-update-plugin ~1.0 -> satisfiable by magento/composer-root-update-plugin[1.0.0].
    - magento/composer-root-update-plugin 1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

```

**Comment by hostep** [comment]
Also see: https://github.com/magento/community-features/issues/302

**Comment by davidncuba** [comment]
Do you know how fix?

**Comment by hostep** [comment]
@davidncuba: stick with composer version 1 (`composer selfupdate --1`) for now until Magento2 is compatible with version 2. This will most likely take 3 to 6 months until it's finished unfortunately.

**Comment by davidncuba** [comment]
@hostep i can't downgrade my composer I use cloudways, do you know if can i do upgrade 2.3.5 out composer?

**Comment by hostep** [comment]
@davidncuba: you have some options I think:
- talk to Cloudways, tell them Magento 2 is currently not compatible with Composer 2 and they will probably consider downgrading Composr for you
- put a `composer.phar` file of your own on the server and use that one instead of the globally installed one

And as you can see in https://github.com/magento/community-features/issues/302#issuecomment-716677169, the Magento developers are giving this a higher priority, so it will probably become available earlier then I originally expected.

**Comment by pdohogne-magento** [comment]
Version 1.1.0 will support up to Composer 2.0.8
